//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 10:07:43 PM EEST 
//


package xsd.jaxb.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for confirmationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="confirmationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="letterBody" type="{http://kiwi.org/PurchaseOrderSchema.xsd}letterBodyType"/>
 *         &lt;element name="webMessage" type="{http://kiwi.org/PurchaseOrderSchema.xsd}webMessageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="confirmation")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmationType", propOrder = {
    "letterBody",
    "webMessage"
})
public class ConfirmationType {

    @XmlElement(required = true)
    protected LetterBodyType letterBody;
    @XmlElement(required = true)
    protected WebMessageType webMessage;

    /**
     * Gets the value of the letterBody property.
     * 
     * @return
     *     possible object is
     *     {@link LetterBodyType }
     *     
     */
    public LetterBodyType getLetterBody() {
        return letterBody;
    }

    /**
     * Sets the value of the letterBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterBodyType }
     *     
     */
    public void setLetterBody(LetterBodyType value) {
        this.letterBody = value;
    }

    /**
     * Gets the value of the webMessage property.
     * 
     * @return
     *     possible object is
     *     {@link WebMessageType }
     *     
     */
    public WebMessageType getWebMessage() {
        return webMessage;
    }

    /**
     * Sets the value of the webMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebMessageType }
     *     
     */
    public void setWebMessage(WebMessageType value) {
        this.webMessage = value;
    }

}
