//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 10:07:43 PM EEST 
//


package xsd.jaxb.output;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xsd.jaxb.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Confirmation_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "confirmation");
    private final static QName _LetterBodyTypeSalutationName_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "name");
    private final static QName _WebMessageTypeMessageText_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "text");
    private final static QName _WebMessageTypeMessageOrderID_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "orderID");
    private final static QName _LetterBodyTypeSalutation_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "salutation");
    private final static QName _LetterBodyTypeShipDate_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "shipDate");
    private final static QName _LetterBodyTypeProductName_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "productName");
    private final static QName _LetterBodyTypeQuantity_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "quantity");
    private final static QName _WebMessageTypeMessage_QNAME = new QName("http://kiwi.org/PurchaseOrderSchema.xsd", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xsd.jaxb.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LetterBodyType }
     * 
     */
    public LetterBodyType createLetterBodyType() {
        return new LetterBodyType();
    }

    /**
     * Create an instance of {@link WebMessageType }
     * 
     */
    public WebMessageType createWebMessageType() {
        return new WebMessageType();
    }

    /**
     * Create an instance of {@link ConfirmationType }
     * 
     */
    public ConfirmationType createConfirmationType() {
        return new ConfirmationType();
    }

    /**
     * Create an instance of {@link LetterBodyType.Salutation }
     * 
     */
    public LetterBodyType.Salutation createLetterBodyTypeSalutation() {
        return new LetterBodyType.Salutation();
    }

    /**
     * Create an instance of {@link WebMessageType.Message }
     * 
     */
    public WebMessageType.Message createWebMessageTypeMessage() {
        return new WebMessageType.Message();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "confirmation")
    public JAXBElement<ConfirmationType> createConfirmation(ConfirmationType value) {
        return new JAXBElement<ConfirmationType>(_Confirmation_QNAME, ConfirmationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "name", scope = LetterBodyType.Salutation.class)
    public JAXBElement<String> createLetterBodyTypeSalutationName(String value) {
        return new JAXBElement<String>(_LetterBodyTypeSalutationName_QNAME, String.class, LetterBodyType.Salutation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "text", scope = WebMessageType.Message.class)
    public JAXBElement<String> createWebMessageTypeMessageText(String value) {
        return new JAXBElement<String>(_WebMessageTypeMessageText_QNAME, String.class, WebMessageType.Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "orderID", scope = WebMessageType.Message.class)
    public JAXBElement<String> createWebMessageTypeMessageOrderID(String value) {
        return new JAXBElement<String>(_WebMessageTypeMessageOrderID_QNAME, String.class, WebMessageType.Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LetterBodyType.Salutation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "salutation", scope = LetterBodyType.class)
    public JAXBElement<LetterBodyType.Salutation> createLetterBodyTypeSalutation(LetterBodyType.Salutation value) {
        return new JAXBElement<LetterBodyType.Salutation>(_LetterBodyTypeSalutation_QNAME, LetterBodyType.Salutation.class, LetterBodyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "shipDate", scope = LetterBodyType.class)
    public JAXBElement<XMLGregorianCalendar> createLetterBodyTypeShipDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LetterBodyTypeShipDate_QNAME, XMLGregorianCalendar.class, LetterBodyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "productName", scope = LetterBodyType.class)
    public JAXBElement<String> createLetterBodyTypeProductName(String value) {
        return new JAXBElement<String>(_LetterBodyTypeProductName_QNAME, String.class, LetterBodyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "quantity", scope = LetterBodyType.class)
    public JAXBElement<BigInteger> createLetterBodyTypeQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_LetterBodyTypeQuantity_QNAME, BigInteger.class, LetterBodyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "orderID", scope = LetterBodyType.class)
    public JAXBElement<String> createLetterBodyTypeOrderID(String value) {
        return new JAXBElement<String>(_WebMessageTypeMessageOrderID_QNAME, String.class, LetterBodyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebMessageType.Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kiwi.org/PurchaseOrderSchema.xsd", name = "message", scope = WebMessageType.class)
    public JAXBElement<WebMessageType.Message> createWebMessageTypeMessage(WebMessageType.Message value) {
        return new JAXBElement<WebMessageType.Message>(_WebMessageTypeMessage_QNAME, WebMessageType.Message.class, WebMessageType.class, value);
    }

}
