//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 11:16:20 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/input", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xsd.jaxb.reply;
